sudo: required
language: ruby
services:
- docker
env:
  global:
  - COMMIT=${TRAVIS_COMMIT::8}
  - REPO=dairyd/buildpack-deps
  - secure: drBU79SHJ7RNQcAFjdIzNsd7t8AIAACeG2Ks+b3MvH1T5bq85OKcTc9l9/rPVlo6ee5uHHOAW9WWujUilDl+5SJGYJTTzhQlqRMLcSPkBxQSH/F9GaGiqJMV90tu2sXmgSvDwDy1ckF2pM0EI0PdW0TH+Ac2TeEKKEbKKWB8NYZDVCKnGVKFABrRH0t2BY6Lh8i1+tDMN0dyPoKh8NvTzKUhcwXW/ew83iValkLoEAbeROgc3kI/Qwf8PQZ1D4dnP2m2m1Zd8qIr2Tk0zgFTyqeNGIWHN9dj9kFiZcSWTvZrbEM0lXRJrmincsuUAQoj4Y7Hw389k+xTQ55It5dhR24VtWaNtRpHgRejxiYplKGJP8BTTBx9PBaoRd5LjLQ0/12f8D/0iL7s2CzcgQ++k/QWD+wKuvZAs5yFwXljV8C3DTxVBiGeDtHT5DDHTiBd1paZ04cWplVqx4r/uNIu1VL21ugHryanN/hqpjUyxk8gy7EQv2VuK1JNYzFpVXZaUft+uTtBx3ysyEElFBYcHkh2r21bXXLtTM8aBun7yUpqDPVGUD+1qXBXI/CxD4NPX7hMsgL4VSRKCX/4dqAY6UDR5eu6En1DwtSGg+cBamKXONplauDitVoA8/TWBzA6wt7g5k1Q88gVscsY6098f2pFJ3a4ei8i9XqbQ1n3gX4=
  - secure: XhfLDvxaL/nughQpGUx9kh26xQ9WFe9rdrztUR13fbbl71OPaAI7fP3o6DxcYP88p3HUQv67QtPwxe3aI/bRWJx0/dd8zQhPdsixTEsnhXhvGdOWB4V2hPsirHpDa2fQ9Ac8G3GWgdUBnsD9Zp/Q9EcMTLaukbCIt/pQPeO5BhsYnIy8W+gANRVG/y2FBcG5xaxrZD3uHg0S1j/fPpzId4Odn81TsKSOBSxloJjF4WEOhobxHUE4LbrysKhXDYWlg8/Ptp090TumIvkv5YeexA49X0j9PTLmB8+UXjaL3tfDHjblnyQzn5icnemmMKEai+4Eh19VCgHgAypdb+B1/CXXU1+YQWb6tbRImoRTTroi+i2xlpznGEn5b4EjK1QSTNcq5/KNVHG3oYJYSJc+3eEgFfAJRKN32oJY0cyLbU+VpmR4BfedzBMnmoscBttQdkkxZOpkxpIVp/I4bsremjmV7v5zaePqDXDk5adkU4jR4Pl+rr1qN7t5hZxyfmbJBwTrX+kv4gPIMvt1eCrUsjhVpAqfDBqu6pE52nPS55gNfKeJEz+UdA4azdVq8iBGyJliDKNWFabTBUP9bv0v6U7Ad2SltfWz0Ex5+7buhXIW6IAJxf/r5pEK3a4l66ux9tvTf9iwQhy6PcgLiK0u2je1no/KoCOp0pgHsXkENRw=
script:
- export TAG=`if [[ $TRAVIS_PULL_REQUEST == "false" ]] && [[ $TRAVIS_BRANCH == "master"
  ]]; then echo "stretch-curl"; else echo $TRAVIS_BRANCH; fi`
- export REPO=dairyd/buildpack-deps
- docker build -t $REPO:$TAG -f Dockerfile .
after_success:
- docker login -u $DOCKER_USER -p $DOCKER_PASS
- docker push $REPO:$TAG
