sudo: required
language: ruby
services:
- docker
env:
  global:
  - COMMIT=${TRAVIS_COMMIT::8}
  - REPO=dairyd/buildpack-deps
  - secure: JFu1OlTbAN6q4NdZy349JMqewcUVkToOm3NX8BZfSJxy38iLaCrx5rydbQXnhc/wObgCx3MYcM7BZOM3p8ltT19nQZHpLAAHI9AxYIIVTo0eQRXwjoGnwuctkeTUJMKTr6EQ1SopFTNEZ+dfzvwHY7pnRjCa6c67wkLuM3wZxEJviip8+5E9fn7ZaYHQo5+jruP31Ugb+c8J62AoCpjHgkoKw4koJlX+7wMMe5TgJ/TxRYze0MNfexDnXZ+9IpmWEdMKX2SbYb/8J3lDJsrvDwTtLovkUmdMVFTxPTKPOQnFS/H64xglm15Mwzy7RHhY/ystZkx/4nniRnjt3R8faUk/nDmWj7DRqZYIfCY+029qCfGbfXPG64T/6/FXIdZkaEmV7EbmbDDfZSrDadYNf04PvqHTk2XTdk+I7fvoDfsLzRfYgIxicQqpX8jTBsgCFZls8zgK6JPlfYpeGWoiDt8f/XoeB8DkgndUmnKockWYun7ozVMa5xzCBUKu467hhU38tS7vlb16vYspgdkengcM663s0s+Nut83q4L+l1HJIo1v8lIwh3RbZJOjiWoSxFRc6dGb90KgRwYdkZgsUyDZW7qm+egQ7oahFur+Vw1OogqU5ZKmCkpvZqKaHxg2UcKTCh+MySRwkG7w+jjK3feRxlQRs07Z3iJ0OJvHeH8=
  - secure: keELpaDvQlC1YtIAA91TS+JTCHXv0CIYglWuZQ+uKF1zFRHCIw9I1IxBdWluV35FHPK/40DiF/GHAa2tySBO/kx6FBCis3B0bi9gH3LxaERT9tbVH6VV+ewwPBrZFvVnmiYcjS6clFB72qTOnz19KQk2sC9V58R1B2Ro0nyakgC5LAg5iHSpCKsWLGhXC3nkGD/+Ez/mG8EuGNJe51Rv7tE/zB2l3EwX5eSgVX7DQNGs8saYm5BZ2vNzGPuZWuZPbZs2DoNv3M1RfFf4SE7cvlE1RKFLw/Gu8bibZxvcJjtzZ2NDhLu1jEIzZzLrx/nDaEqaPaLuPgOMR8kp9/40oVS1BjTBZpfAD5l5SyM7rex63JtM01UhOWgDq0jfXGTBVsWBvogR6SX8HL+lINwIAltTqK96LEkQKh8TsIEwNx+U6QUbmrtYQ2Q+1JKCGaG8ViQnkTTyCCaAyGcZaa0+PJV+1Lf/C+ZafOpMeNU4zJVeEzDr1izH17Yu2vR1xE4yACCgwsWXlLWmNcQLQqjnOBYZcXbtnzOUULctXDMqF1T6h8aLAOEWu0kzpd9CUZdG/HMrZvyPxB/0F4sKWEt5R27+0yZIEITIipA3Me88evHHBGLCXfe4zwjWI4aqj8t8/RdzQc1T8ZyZoBCD7NuiLsnXWlsHtbur4yaNQ8dtCTA=
script:
- export TAG=`if [[ $TRAVIS_PULL_REQUEST == "false" ]] && [[ $TRAVIS_BRANCH == "master"
  ]]; then echo "stretch-curl"; else echo $TRAVIS_BRANCH; fi`
- export REPO=dairyd/buildpack-deps
- docker build -t $REPO:$TAG -f Dockerfile .
after_success:
- docker login -u $DOCKER_USER -p $DOCKER_PASS
- docker push $REPO:$TAG
