sudo: required

language: ruby

services:
- docker

env:
  global:
  - COMMIT=${TRAVIS_COMMIT::8}
  - REPO=dairyd/buildpack-deps
  - secure: fsfUWqyP7cAT331yTEOBaEaAhSQQKs7QIYpKsHd6bXAiOwK+Sxr+cA/0+Hiix5Q3EEIK/DtlxHeuHnOM33Ai78xg4eRportyk7/8mKF6d2SkpZ8FB2c1p7Yrh+BtIPufCrRoH5SIx1zg7vwHxlLD6NPBbVJH7IDy0/zNywO6Y6ADaAD58GGZhPH4WEIMvuCNcLJlJp01zUcAZoxcwjjEZuHq4gOR23gASjXvog3NA22+IEt5vU3QaExfjAAfzFJEVwU336EecBa3WozT15Z0RGlM630j5aiOPQL7wDeCi2qnKCBBn4+sf8FNcMIDlCaWJDcY93VOUCT25awxa8GEyB7buVRcKCVSXuzog/9nCn/HIyaQ7C4s1gFUHfdjCYtoGNV2FQ1jzQNXIZW06Xw0By1tBe8roB0hgZCvslg+DM1CdaXhjb9tiOx25m8iSMo4jUvU00/APQ72xWB5YLbupZsNfrqNKtHJ8xl/+cES4G+zKZc9svrHFZnCsFYElvuBBsD3JhB59LQ5EuQ4aKn807Nd/7U3TFyWVfbRPTRkZp+cImzz1DH5DO11PqsazAcg9wg5rC9Cf7RO7+N3IXYTErrTY+4L7kmY8fOMJyMDSzS56CWTDl9MibElxGT6llQSijOj9cXJvHmWfhYMcb20Qh9iE3LXzzj9jVXQPtpULtU=
  - secure: c/T/+27wqmGmv67Kh9I4wm0JO4oDqzB3St42knKMwwaHVGFBQMKKc8opXb7rRmEh0KL2US3ZKH6s1AuFxKkjV7mWkfZPd+6i1tHhr/GyMM13NPmwm4UpB3uOBSdDvWUVXUYBqg2t5o/GP/rfogEPta/50VRCY4VAzK3UVW6FpMkI2CECOknUL/drVgy26Ae4oSK9vxyrRu4UcB9unyXTH+rKRfqLpAbsN+9/5/qu96GYBuvpeA8pHmc6qThI2+7+EqL9VLuyUes049ZRI7A25bixAFtnpz/cbjmaRxFbMMNRhfDQB2ImXkS3WABuxsnDmQrqwtee4sh+O20tgMRMoJqYYvu4MMGu1RB0iNIM5AQnX07jS66qZ5+/MdukhpBGeMO0ywTFGeM9l3Y9jVrk8KaN3SA16dUr/1GU7tamayACIs3WHAbYPUagd+qKROd2nB1GBxaiPT0PjXJ2yCEjsM6dNdJsedEaXLpltjHqveS0RjxyXxKxLEem0+aB/kG6zQElpMscaYourP2LvtRng/rKJ6NClB9klaf/9kXf0MyOrhKImbTGHToEoocGJ0ZhFI6AkXbCtQ9F6tsiUFTVm6tnhf+JYNbCWlBq0bIbYpkozcBVas3z8LCXIxl1KnGzcjV0ONPMFFx8wfsoUZJyXVIpq2OSd2wYs9yU2HqYHL4=
  - secure: qOm8EMfS5CWoY18+SVhcZdOTbpuALZMib/qPYH9TMQyvh6jlOjrO6FfmB9XIIcjrj6SSMfDv0KWp3uUB5XxWrtwCv6qkRhG5aaM72SNn2Jjt40uE6rm4jbG3SWNk2H7O6umRBHiX/rLtf6QzLQct+R7/6bqrwXif+SfCmskUU2S14AlEwY+UOekRIQToNqJx9YP1U8+gt/bGDYTDOKH0VnDJ5U0qQKtT9sA88HdL/qPOHOd0f5jcElrG5htIlbiKC7+C80wcelRC281v9OJ8O/PEgmh13IpGDVD+emW+KE/WwTjb9jBuPb0Oi5wRl0MQHHFvnuKEi1rO6DcWd3UaQ1RXOEGi77jDiirZ+ppYJbFVD4GYtLSFm0nifNSIo7/lNoSL3uvLNrmWLJShXCD9wnB4Ujuq2IcMlj/yBGyTQqfH5C64+7UWriWaQGdajZQOiUiI6tn3AGm+vmjyr2bN4hobAEBkg8eQOV0NHtyNM1mjJlR2jJbAXjS3XGtYjJzoIfXK6WoKqHUvH6aye4sfl2PgOjKdHvx4p6/sm23Uf/zJcZa/f7dmGKK4IeOxiRFhUGzwpDdwlZAWQyWKBQKjO9/zxo+CLs9FdDNJa73NFgzq6LmAuo3GIbYf1Pg6BZgamvS1sVDqIA5wU8sThDze2xLfluC9xJQ0BaplLUf1q58=

script:
- export TAG=`if [[ $TRAVIS_PULL_REQUEST == "false" ]] && [[ $TRAVIS_BRANCH == "master"
  ]]; then echo "stretch-curl"; else echo $TRAVIS_PULL_REQUEST_BRANCH; fi`
- export REPO=dairyd/buildpack-deps
- docker build -t $REPO:$TAG -f Dockerfile .

after_success:
- docker login -u $DOCKER_USER -p $DOCKER_PASS
- docker push $REPO:$TAG
