sudo: required

language: ruby

services:
- docker

env:
  global:
  - COMMIT=${TRAVIS_COMMIT::8}
  - REPO=dairyd/buildpack-deps

script:
- export TAG=`if [[ $TRAVIS_PULL_REQUEST == "false" ]] && [[ $TRAVIS_BRANCH == "master" ]]; then echo "stretch-curl"; else echo $TRAVIS_BRANCH; fi`
- export REPO=dairyd/buildpack-deps
- docker build -t $REPO:$TAG -f Dockerfile .

after_success:
- docker login -u $DOCKER_USER -p $DOCKER_PASS
- docker push $REPO:$TAG
